### ISSUE TITLE
Can't use new authentication

### ISSUE THREAD

**Issue by ASullet** [giacbrd/python-dandelion-eu#12]
Apparently, we don't need any "app_id" anymore but this is still required in the python API.
The problem is that we can't create it on the website.
Thanks

**Comment by yakovkeselman** [comment]
I found the following piece of code to work (with Python3):
`TOKEN = '...your_token...'`
`from dandelion import DataTXT`
`datatxt = DataTXT(app_id=TOKEN, app_key=TOKEN)`
`response = datatxt.nex('The doctor says an apple is better than an orange')`
`for annotation in response.annotations:`
`    print(annotation)`

**Comment by giacbrd** [comment]
Hi, explicit authentication by token will be added in the next release
cheers
