### ISSUE TITLE
Is this alive or dead?

### ISSUE THREAD

**Issue by 1oglop1** [giacbrd/python-dandelion-eu#13]
@vad is this still being maintained?
There are few PRs and Issues without reaction.

**Comment by vad** [comment]
@1oglop1 dead. We'll move it out of the company account. If you'd like to fork it and keep it updated you're more than welcome!

**Comment by giacbrd** [comment]
Hi @1oglop1 , I am resuming this repo, fixing deprecated stuff in order to make everything stable.
Cheers
