### ISSUE TITLE
unable to set parameter "lang " , when using text similarity , throws error 

### ISSUE THREAD

**Issue by nayakvidya** [giacbrd/python-dandelion-eu#14]
datatxt.sim(txt1,txt2, "en") gives error . How to specify english language when giving similarity

**Comment by giacbrd** [comment]
hi, you should explicitly set the parameter `lang` as described in https://dandelion.eu/docs/api/datatxt/sim/v1/ , only the `text1` and `text2` parameters are positional in Python API, so:
```
datatxt.sim(txt1,txt2, lang="en")
```
