### ISSUE TITLE
HTTP response code is not checked before doing any parsing

### ISSUE THREAD

**Issue by RiccardoMaffei** [giacbrd/python-dandelion-eu#5]
HTTP response code is not checked before doing any parsing in base.py and this may lead to parsing exceptions.
A scenario I've been running into lately:
- Query nex API with some text
- The request takes too much time
- 504 is returned from your gateway
- base.py tries to decode the response as JSON (ignoring return code)
- json decode raises ValueError (as expected)
https://github.com/SpazioDati/python-dandelion-eu/blob/f9ce3b693b0818bb5d177b4771e2e29bf35858d5/dandelion/base.py#L86 

Ignoring the reason why the request took so much time, the client library should check the return code.

**Comment by giacbrd** [comment]
Hi @RiccardoMaffei , it will be fixed in the next release
cheers

**Comment by RiccardoMaffei** [comment]
Perfect!
