### ISSUE TITLE
Input type parameters are hard-coded

### ISSUE THREAD

**Issue by RiccardoMaffei** [giacbrd/python-dandelion-eu#6]
**_DataTXT_** APIs have more than one input type such as **_plain text_**, **_url_**, **_html fragment_** and others. 
They are implemented as required and mutually exclusive parameters as described in [API documentation](https://dandelion.eu/docs/api/). 

Currently in this library some of them are hard-coded preventing the user to choose the right one. 
In particular, at the moment the only content type available is **plain text** since it's hard-coded in the following lines:
- https://github.com/SpazioDati/python-dandelion-eu/blob/f9ce3b693b0818bb5d177b4771e2e29bf35858d5/dandelion/datatxt.py#L13
 - https://github.com/SpazioDati/python-dandelion-eu/blob/f9ce3b693b0818bb5d177b4771e2e29bf35858d5/dandelion/datatxt.py#L18
 - https://github.com/SpazioDati/python-dandelion-eu/blob/f9ce3b693b0818bb5d177b4771e2e29bf35858d5/dandelion/datatxt.py#L23

**Comment by giacbrd** [comment]
Hi @RiccardoMaffei (I am resuming this repo) I have simply solved this by setting the `text` arguments as optional, with a default, empty string value

**Comment by RiccardoMaffei** [comment]
Hi @giacbrd I must admit that it's been a while since I looked at the implementation however, if I understand what you mean, I think this solution may not work.
Even if you set the `text` argument as optional here
https://github.com/giacbrd/python-dandelion-eu/blob/f9ce3b693b0818bb5d177b4771e2e29bf35858d5/dandelion/datatxt.py#L9
the (now None or empty) parameter is still added (hardcoded) to the dictionary of request parameters here
https://github.com/giacbrd/python-dandelion-eu/blob/f9ce3b693b0818bb5d177b4771e2e29bf35858d5/dandelion/datatxt.py#L12-L14
and following the call stack, the parameter `text` will eventually be added to the actual API request here.
https://github.com/giacbrd/python-dandelion-eu/blob/bd622aeff3247c885b4dc4f534c6df8093732216/dandelion/base.py#L99-L107

I guess there's no "clean" solution to this issue. 
For example you may completely remove the parameter from the definition and then, when users calls the function using it (or `url`, `html` etc) this will end up in `params` dictionary and everything will work as it should be (Cleaner but the user may need to look ad the documentation in order to know the parameter name. You may also implement some error checking if you want). 
Otherwise you could add all 4 parameters (`text`, `url`, `html`, `html_fragment`) in the definition as optional with default `None`, in the function body enforcing that one and only one of them must be non-None (throwing an exception otherwise) and then adding only that one to the dictionary like you are doing now with `text` here. https://github.com/giacbrd/python-dandelion-eu/blob/f9ce3b693b0818bb5d177b4771e2e29bf35858d5/dandelion/datatxt.py#L12-L14
If you don't want to throw an exception, just use the first non-None parameter and ignore the others. 
 
None of these solutions are clean but will let the library user access all API features.

**Comment by giacbrd** [comment]
Hi @RiccardoMaffei , I understand your concern. I think this is the slimmest solution to the main problem we had here: if one set `html` parameter and not `text` he receives an exception. Now both the 4 content parameters can be empty, in this case one will receive the right error from Dandelion API. I would prefer to not check the parameters in the code and throw an exception which is practically identical to the API's one. I could probably definitely remove the `text` parameter, but I will leave it there for retro-compatibility, i.e., if one already calls the method without the keyword argument `text`

**Comment by RiccardoMaffei** [comment]
Hi @giacbrd, I understand you don't want to implement client-side error checking.
I still think you must completely remove the argument `text` from the function and don't manually add it to the dictionary in the body.
In this way users can still use `text` (or all the other alternatives) just by setting the named argument because it will end up being inside `**params`.
Something like this 
```python
def nex(self, **params):
    if 'min_confidence' not in params:
        params['min_confidence'] = 0.6
    return self.do_request(
        params, ('nex', 'v1')
    )
```
called like this
```python
obj.nex(text='...') # or obj.nex(html='...')...
```

The problem with leaving the `text` argument are:
- if you also leave the following line as is (continue adding it to the dictionary) the whole issue is not  fixed and prevents users from using **something different** than `text`. https://github.com/giacbrd/python-dandelion-eu/blob/f9ce3b693b0818bb5d177b4771e2e29bf35858d5/dandelion/datatxt.py#L13
- otherwise if you don't add it to the dictionary (removing the `text` part from the previous line) the argument becomes useless **and** prevents users from using `text` at all.

**Comment by RiccardoMaffei** [comment]
Hi @giacbrd, I understand you don't want to implement client-side error checking.
I still think you must completely remove the argument `text` from the function and don't manually add it to the dictionary in the body.
In this way users can still use `text` (or all the other alternatives) just by setting the named argument because it will end up being inside `**params`.
Something like this 
```python
def nex(self, **params):
    if 'min_confidence' not in params:
        params['min_confidence'] = 0.6
    return self.do_request(
        params, ('nex', 'v1')
    )
```
called like this
```python
obj.nex(text='...') # or obj.nex(html='...')...
```

The problems leaving the `text` argument are:
- if you also leave the following line as is (adding it to the dictionary) the whole issue is not  fixed and prevents users from using **something different** than `text`. https://github.com/giacbrd/python-dandelion-eu/blob/f9ce3b693b0818bb5d177b4771e2e29bf35858d5/dandelion/datatxt.py#L13
- otherwise if you don't add it to the dictionary (removing the `text` part from the previous line) the argument becomes useless **and** completely prevents users from using `text`.

**Comment by giacbrd** [comment]
Hi @RiccardoMaffei yes I must remove the "forced" argument in 
https://github.com/giacbrd/python-dandelion-eu/issues/6#L13
but I must keep text as first argument in `nex`. This is because if someone has this in his codebase:
```nex("this is text bla bla")```
and he decides to update this library,
removing the explicit `text` argument would break his code

**Comment by RiccardoMaffei** [comment]
Hi @giacbrd I understand why you want to leave it there. This is exactly the reason why one of my previous suggestion was to do something like this:
```python
def nex(self, text=None, html=None, html_fragment=None, url=None, **params):
    if 'min_confidence' not in params:
        params['min_confidence'] = 0.6
    # here find the first non-none argument 
    # and "force" add it to the params dictionary
    return self.do_request(
        params, ('nex', 'v1')
    )
```
This will be retro-compatible.

If I have understood correctly you want to do something like this:
```python
def nex(self, text=None, **params):
    if 'min_confidence' not in params:
        params['min_confidence'] = 0.6
    return self.do_request(
        params, ('nex', 'v1')
    )
```
but this will completely prevents users from using `text`.

To be fair you could do something like this but it's even dirtier:
```python
def nex(self, text=None, **params):
    if 'min_confidence' not in params:
        params['min_confidence'] = 0.6
    if text is not None:
        params['text'] = text
    return self.do_request(
        params, ('nex', 'v1')
    )
``` 
In this way `text` will be captured by the argument and added (only if not None) to the dictionary while other input-types such as `html` will automatically end up in the dictionary. Exceptions will be handled by the API itself. This will be retro-compatible.
What do you think?
